In [1]:
import os
os.chdir("..") # Ek folder piche jane ke liye
print(os.getcwd()) # Check karein ke ab path 'psl_ai_platform' par hai ya nahi

c:\Users\User\Desktop\psl_ai_platform

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("data/processed/ball_by_ball/psl_ball_by_ball_clean.csv")
dismissal_df = df[(df["wicket"] == 1) & (df["player_out"].notna())].copy()
dismissal_df.head()

Empty DataFrame
Columns: [match_id, innings_number, batting_team, over, ball, batter, bowler, non_striker, runs_batter, runs_extras, runs_total, extras_type, wicket, wicket_type, player_out, fielders_involved, match_date, city, venue, team1, team2, toss_winner, toss_decision, phase, ball_id]
Index: []

[0 rows x 25 columns]

In [4]:
player_name = "Babar Azam"
player_df = dismissal_df[dismissal_df["player_out"] == player_name].copy()
player_df.head()

Empty DataFrame
Columns: [match_id, innings_number, batting_team, over, ball, batter, bowler, non_striker, runs_batter, runs_extras, runs_total, extras_type, wicket, wicket_type, player_out, fielders_involved, match_date, city, venue, team1, team2, toss_winner, toss_decision, phase, ball_id]
Index: []

[0 rows x 25 columns]

In [5]:
phase_wicket = pd.pivot_table(
    player_df,
    index="phase",
    columns="wicket_type",
    values="match_id",
    aggfunc="count",
    fill_value=0,
)
phase_wicket

Empty DataFrame
Columns: []
Index: []

In [8]:
# Check karein ke kitne records mile
print(f"Total dismissals found for {player_name}: {len(player_df)}")

# Agar data khali hai, to unique names check karein ke file mein kya naam likha hai
if len(player_df) == 0:
    print("Available players in dismissal data:")
    print(dismissal_df["player_out"].unique()[:10]) # Pehle 10 naam check karein

Total dismissals found for Babar Azam: 0
Available players in dismissal data:
[]

In [9]:
if not phase_wicket.empty:
    plt.figure(figsize=(10, 6))
    sns.heatmap(phase_wicket, annot=True, fmt="g", cmap="Reds")
    plt.title(f"{player_name} — Phase vs Wicket Type")
    plt.show()
else:
    print(f"Oops! {player_name} ka koi dismissal record nahi mila, isliye graph nahi ban sakta.")

Oops! Babar Azam ka koi dismissal record nahi mila, isliye graph nahi ban sakta.

In [10]:
plt.figure(figsize=(10, 6))
sns.heatmap(phase_wicket, annot=True, fmt="g", cmap="Reds")
plt.title(f"{player_name} — Phase vs Wicket Type")
plt.show()

ValueError: zero-size array to reduction operation fmin which has no identity

In [7]:
bowler_wicket = pd.pivot_table(
    player_df,
    index="bowler",
    columns="wicket_type",
    values="match_id",
    aggfunc="count",
    fill_value=0,
)
bowler_wicket.head(10)

Empty DataFrame
Columns: []
Index: []